### PR TITLE
fix(ci): unblock PBT nightly on Kotlin 2.4.x and 2.3.20 lower-bound

### PR DESCRIPTION
**Pull request by TBSten**
## Summary

PBT nightly run [#25611298765](https://github.com/TBSten/compose-preview-lab/actions/runs/25611298765) failed in two matrix entries because the workflow drifted from `scripts/supported-kotlin-versions.txt` and one upstream Kotlin API moved.

- **Kotlin 2.4.0-Beta1 entry → `Publish to Maven Local` failed** during `:compiler-plugin:compileKotlin` with `Too many arguments for 'fun FirAnnotation.getBooleanArgument(name: Name): Boolean?'`. The stdlib helper dropped its `session: FirSession` parameter in 2.4.0-Beta1, so the direct call in `PreviewHintFirGenerator.kt` no longer compiles against any 2.4.x baseline. Routed the call through a new `CompatContext.getBooleanArgumentCompat(...)` SPI so each compat module targets its own API shape (2-arg for `compat-k210/k222/k230`, 1-arg for `compat-k240_beta2`). Locally verified by switching `gradle/libs.versions.toml` to `kotlin = "2.4.0-Beta2"` + `compose = "1.11.0-alpha04"` and running `./gradlew :compiler-plugin:compileKotlin` (BUILD SUCCESSFUL), then restoring.
- **Kotlin 2.3.20 entry → `Run Integration Test PBT` failed** with `[ComposePreviewLab] collectAllModulePreviews() requires Kotlin 2.3.21 or later for cross-module preview aggregation.` That diagnostic is intentional (added in 6f8ef741); both the integrationTest app and docs sample use `collectAllModulePreviews()`, so they cannot compile on the 2.3.20 lower bound by design. Tagged the 2.3.20 matrix entry with `skip_cross_module_apps: true` and gated the two app-compilation steps so the entry now exercises only Library PBT (`collectModulePreviews()` lower bound).
- Bumped the upper-bound matrix entry from `2.4.0-Beta1` → `2.4.0-Beta2` to match `scripts/supported-kotlin-versions.txt` (the version with a published `compat-k240_beta2`).

## Test plan

- [ ] Re-run PBT nightly via `workflow_dispatch` (or wait for the next 5:00 JST cron) and confirm all three matrix entries pass:
  - [ ] `default` (current libs pin) — Library + Integration + Docs
  - [ ] `Kotlin 2.3.20` — Library only (Integration + Docs skipped)
  - [ ] `Kotlin 2.4.0-Beta2` — Library + Integration + Docs
- [ ] Confirm `getBooleanArgumentCompat` dispatches correctly: `@ComposePreviewLabOption(ignore = true)` previews still get filtered out of hint emission on 2.3.x and on 2.4.0-Beta2 (covered by existing `PreviewHintIgnoreCrossModuleTest` / `PreviewDiscoveryTest`).
- [x] `./gradlew ktlintCheck :compiler-plugin:compileKotlin :compiler-plugin:test --continue` — BUILD SUCCESSFUL on the current 2.3.21 baseline.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: .github/workflows/pbt-nightly.yml [hunk 1]
```diff
@@ -26,10 +26,15 @@ jobs:
             compose_version: '1.11.0-alpha04'
             gradle_version: ''
             name: 'Kotlin 2.3.20'
-          - kotlin_version: '2.4.0-Beta1'
+            # `collectAllModulePreviews()` requires Kotlin 2.3.21+ (see
+            # `scripts/supported-kotlin-versions.txt`); the integrationTest / docs apps
+            # both use it and would fail to compile here. Library PBT alone exercises the
+            # `collectModulePreviews()` lower bound, which is what 2.3.20 is meant to cover.
+            skip_cross_module_apps: true
```
Comment (TBSten) [inline .github/workflows/pbt-nightly.yml]: ごめん、やっぱり 2.3.20 -> 2.3.21 を周回するようにして 🙏

Comment (TBSten) [reply .github/workflows/pbt-nightly.yml]: その結果 skip_cross_module_apps はいらなくなるはず
